# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0b07e4808e069279ddb2a4fe5dc8b8a222f0b82dafd9a2a7c9e6f93c26a572dd2dde46c702d1490d5f919d4afc482b84ee0895c5f1f8cd12adee699d75327d0

test:
  secret_key_base: 60b7fdd34b59f2d33aa929f9e008b7bc2603ac6d76cb18add5fea7a7aac978d79d6d091aa98b75de07c378cccd015141f2dd9f06bae9b0780167632e55722642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
